version: '2.3'
#network_mode: "bridge"
services:
  ad_server:
    build: server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
    depends_on:
      - postgres
    ports:
      - "18080:18080"
    networks:
      - ad_server_network

  redis:
    image: redis:latest
    networks:
      - ad_server_network
    restart: unless-stopped


  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - ad_server_network
networks:
  ad_server_network:
volumes:
  postgres: