version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  ad_server:
    build: server
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
    networks:
      - postgres
    depends_on:
      - postgres
    ports:
      - "18080:18080"

volumes:
  postgres:
networks:
  postgres:
