name: Go

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work_dir:
          - ./server/
    steps:
      - uses: actions/checkout@v3

      - name: Test
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...
